### ISSUE TITLE
Add support for search templates

### ISSUE THREAD

**Issue by newoga** [englishtown/vertx-elasticsearch-service#13]
Thanks for making this service...

We are interested in adding support for [search templates](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-search-template.html). Our company forked this project and ultimately will have to update the version of the version of the elasticsearch driver to support it. Long term we would like to be able merge our changes into this repository, but I wanted to see what you had in mind long term for this repo and see whether or not these changes would be in line with what you wanted to achieve with the project (in regards to API simplicity,  support for older versions of the java client/database, or anything else). 

Let me know and thanks again!

**Comment by adrianluisgonzalez** [comment]
I was planning to update the driver to 1.7.0 shortly.  I've been adding functionality as it has been needed or as pull requests have come in. 

If you want to submit a PR for the search template support that would be great.

Thanks!

**Comment by newoga** [comment]
Awesome, I'll get you a PR soon.  Also, I found out I was wrong and all this stuff is supported in 1.4 anyhow so I didn't have to update the driver :)
