### ISSUE TITLE
any plan to migrate over to guice

### ISSUE THREAD

**Issue by alanma** [englishtown/vertx-elasticsearch-service#19]
Since englishtown cassandra is using guice, and IMHO guice is more preferred by Java developers, do you have any plans to move hk2 to guice? It would make developers who use your cassandra and elastisserach service together much easier. Please do share your thoughts on hk2 vs guice if possible. Thanks.

**Comment by adrianluisgonzalez** [comment]
I have added a guice binder and integration tests using guice.

While I prefer guice, we use jersey which internally uses hk2 making integration a little smoother.  Overall we try to stay DI framework agnostic (apart from binders obviously).
